apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.postgres.service.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.postgres.service.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.postgres.service.name }}
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: {{ .Chart.Name }}-env
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgres.service.name }}
spec:
  selector:
    app: {{ .Values.postgres.service.name }}
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP